services:
  backend:
    build: .
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "db", "-pbel4013", "--silent" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    restart: always
    environment:
      - MYSQL_DATABASE=tareas
      - MYSQL_ROOT_PASSWORD=bel4013
    expose:
      - 3306
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - 3333:8080